config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers :authorizations => 'authorizations'
    controllers :applications => 'applications'
  end

  authenticated :user do
    root :to => 'users#show', :as => :authenticated_root
  end

  root :to => redirect('/users/sign_in')

  devise_for :users, :controllers => {
                       :confirmations => 'confirmations',
                       :sessions  => 'sessions',
                       :checkga => 'checkga'
                   }

  as :user do
    patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
  end

  resource :user, only: [:show, :edit, :update]
  resource :help, :controller => 'help' do
    get :download_manual
  end

  namespace :admin do
    get '/' => 'admin#index'
    resources :users
  end

  namespace :api, :defaults => {:format => :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true), :defaults => {:format => :json} do
      get '/me' => 'credentials#me'
      resources :applications
    end
  end
end

app/views/menus/_admin.html.erb
<%= link_to t('admin.users'), admin_users_path %>
<%= link_to t('admin.oauth'), oauth_applications_path %>

app/views/menus/_menu.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to t('application.name'), root_path, :class => 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= t('help.help') %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to t('help.download_manual'), download_manual_help_path %></li>
          </ul>
        </li>
        <% if user_signed_in? %>
            <% if current_user.has_role?(:admin) %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= t('admin.administration') %> <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= render 'menus/admin' %></li>
                  </ul>
                </li>
            <% end %>
            <li class="divider-vertical"></li>
            <%= render 'menus/my_account', :app_config => APP_CONFIG, :user => current_user, :my_account_path => user_path, :gravatar_url => current_user.gravatar_url(:size => 20) %>
        <% else %>
            <%= render 'devise/menu/login_items' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>