config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers :authorizations => 'authorizations'
    controllers :applications => 'applications'
  end

  authenticated :user do
    root :to => 'users#show', :as => :authenticated_root
  end

  root :to => redirect('/users/sign_in')

  devise_for :users, :controllers => {
                       :confirmations => 'confirmations',
                       :sessions  => 'sessions',
                       :checkga => 'checkga'
                   }

  as :user do
    patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
  end

  resource :user, only: [:show, :edit, :update]
  resource :help, :controller => 'help' do
    get :download_manual
  end

  namespace :admin do
    get '/' => 'admin#index'
    resources :users
  end

  namespace :api, :defaults => {:format => :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true), :defaults => {:format => :json} do
      get '/me' => 'credentials#me'
      resources :applications
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :gauth_token
  include Gravtastic
  gravtastic :secure => (AppConfig.get(%w(user_profiles secure), APP_CONFIG) ? AppConfig.get(%w(user_profiles secure), APP_CONFIG) : false)

  devise :google_authenticatable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable

  has_many :user_applications
  has_many :applications, :through => :user_applications

  include RoleModel
  roles :admin, :user

  validates :fname, :presence => true
  validates :lname, :presence => true

  before_save :set_roles
  before_create :set_time_zone

  ROLE_DESCRIPTIONS = {
      :admin  => 'Can create/edit/delete users.',
      :user  => 'Basic user.'
  }

  def full_name
    "#{self.fname} #{self.lname}"
  end

  def full_name_comma
    "#{self.lname}, #{self.fname}"
  end

  def only_if_unconfirmed
    pending_any_confirmation {yield}
  end

  def attempt_set_password(params)
    p = {}
    p[:password] = params[:password]
    p[:password_confirmation] = params[:password_confirmation]
    update_attributes(p)
  end

  def password_required?
    super if confirmed?
  end

  # new function to return whether a password has been set
  def has_no_password?
    self.encrypted_password.blank?
  end

  def password_match?
    self.password == self.password_confirmation
  end

  private
  def set_roles
    self.roles << :user unless self.has_role?(:user)
  end

  def set_time_zone
    self.time_zone = Time.zone.name unless self.time_zone
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def edit
    @user = User.find(params[:id])
    @applications = Doorkeeper::Application.order(:name)
  end

  def create
    user_account_params = user_params

    @user = User.new(user_account_params)

    if @user.save
      flash[:notice] = t('users.created_user')
      redirect_to admin_user_path(@user)
    else
      render :action => 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    user_account_params = user_params

    if user_account_params[:password].blank?
      user_account_params.delete(:password)
      user_account_params.delete(:password_confirmation)
    end

    if @user.update_attributes(user_account_params)
      flash[:notice] = t('users.updated_user')
      redirect_to admin_users_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = t('users.deleted_user')
      redirect_to admin_users_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :time_zone, :fname, :lname, roles: [], application_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_filter :set_user

  def show
    @applications = Application.authorized_for(@user)
  end

  def edit
  end

  def update
    account_update_params = user_params

    if account_update_params[:password].blank?
      account_update_params.delete('password')
      account_update_params.delete('password_confirmation')
    end

    if @user.update(account_update_params)
      # Sign in the user by passing validation in case their password changed
      sign_in @user, :bypass => true
      flash[:notice] = t('users.updated_user')
      redirect_to root_path
    else
      render t('general.crud.edit')
    end
  end

  private
  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation, :time_zone, :fname, :lname, :enable_gravatar)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :email %>
      <%= @user.email %>
    </div>

    <% if @user.pending_reconfirmation? %>
        <div class="field">
          Currently waiting confirmation for: <%= resource.unconfirmed_email %>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :fname, t('users.first_name') %><br>
      <%= f.text_field :fname %>
    </div>

    <div class="field">
      <%= f.label :lname, t('users.last_name') %><br>
      <%= f.text_field :lname %>
    </div>

    <div class="field">
      <%= f.label :password %>&nbsp;<i>(leave blank if you don't want to change it)</i>
      <%= f.password_field :password, :autocomplete => 'off' %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="field">
      <%= f.label :time_zone, t('users.time_zone') %>
      <%= f.collection_select :time_zone, ActiveSupport::TimeZone.all, :name, :to_s %>
    </div>

    <div class="field">
      <%= f.label :enable_gravatar, t('users.enable_gravatar') %>
      <%= f.check_box :enable_gravatar %>
    </div>

    <div class="actions">
      <%= f.submit 'Update' %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<h1><%= t('users.your_account') %></h1>

<div class="my_account">
  <%- if show_gravatar(APP_CONFIG) -%>
  <div class="profile_image">
  <%= link_to(image_tag(@user.gravatar_url), 'https://en.gravatar.com/', :title => 'Change at https://en.gravatar.com/', :target => '_blank') %>
  </div>
  <%- end -%>
  <div class="user_attributes">
    <strong><%= t('users.email_address') %></strong>: <%= @user.email %><br />
    <strong><%= t('users.time_zone') %></strong>: <%= @user.time_zone %><br />
    <strong><%= t('users.enable_gravatar') %></strong>: <%= @user.enable_gravatar? ? t('general.yes') : t('general.no') %><br />
    <br />
    <strong><%= t('applications.authorizations') %></strong>: <%= link_to t('general.show'), oauth_authorized_applications_path, :target => '_blank' %><br />
  </div>
  <br />
  <div class="row">
    <div class="col-sm-6 col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading"><%= t('applications.allowed') %></div>

        <table class="table">
        <tr>
          <th><%= t('applications.name') %></th>
        </tr>
        <% (@user.applications.sort_by { |a| a.name }).each do |a| %>
          <tr><td><%= a.url =~ URI::regexp ? link_to(a.name, a.url) : a.name %></td></tr>
        <% end %>
        </table>
      </div>
    </div>
    <div class="col-sm-6 col-md-6">
      <div class="row">
        <div class="panel panel-default">
          <div class="panel-heading"><%= t('users.roles') %></div>

          <table class="table">
            <tr>
              <th><%= t('users.roles.name') %></th>
              <th><%= t('users.attributes.description') %></th>
            </tr>
          <% @user.roles.each do |r| %>
            <tr>
              <td><%= r %></td>
              <td><%= User::ROLE_DESCRIPTIONS[r] %></td>
            </tr>
          <% end %>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="panel panel-default">
          <div class="panel-heading"><%= t('users.attributes.additional') %></div>

          <table class="table">
            <tr>
              <th><%= t('users.attribute') %></th>
              <th><%= t('users.attributes.description') %></th>
              <th><%= t('general.tables.actions') %></th>
            </tr>
            <tr>
              <td><%= t('users.google_authenticator_enabled') %></td>
              <td><%= current_user.gauth_enabled == '1' ? t('general.yes') : t('general.no') %></td>
              <td><%= link_to t('general.manage'), user_displayqr_path %></td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_user_path %>